### ISSUE TITLE
Make this DB more usable

### ISSUE THREAD

**Issue by n-rodriguez** [markets/awesome-ruby#865]
Hi there!

I'd like to make this "kind of DB" more usable : today it's just a README file and a lot of text within.

What I propose is to create a data directory which would contain all informations within YAML files and a small Ruby script to compile/update the README file.

The data directory would look like :

```sh
data/
├── abstraction
├── admin_interface
└── analytics
...
```
We would create one YAML file per gem with this content :

```yaml
---
gem_name: bcrypt
project_name: bcrypt-ruby
homepage: https://github.com/codahale/bcrypt-ruby
description: bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() password hashing algorithm.
```

After that we could write a small API to retrieve informations from that DB :

```ruby
gem = AwesomeRuby.find('bcrypt')
puts gem.gem_name
puts gem.homepage
```

What I have in mind is a script that would parse your `Gemfile` and tell you how awesome it is :)

A bit like [LicenseFinder](https://github.com/pivotal-legacy/LicenseFinder) :)
